services:
  db:
    container_name: sebania-db
    image: postgres:17
    ports:
      - "5432:5432"
    volumes:
      - sebania_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 3s
      timeout: 3s
      retries: 10
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_DB: ${DATABASE_NAME}

  api:
    image: sebania/sebania:${SEBANIA_VERSION:-0.1.0}
    build: &build-sebania
      dockerfile: Dockerfile
    container_name: sebania-api
    ports:
      - "8000:8000"
    depends_on: &db-healthy
      db:
        condition: service_healthy
    environment: &env-variables
      DJANGO_SETTINGS_MODULE: ${DJANGO_SETTINGS_MODULE}
      DATABASE_HOST: db
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      SMTP_PORT: ${SMTP_PORT}
      DROPBOX_REFRESH_TOKEN: ${DROPBOX_REFRESH_TOKEN}
      DROPBOX_SECRET: ${DROPBOX_SECRET}
      DROPBOX_KEY: ${DROPBOX_KEY}
      WHISPER_MODEL_DIRECTORY: /app/whisper/
      WHISPER_MODEL: ${WHISPER_MODEL}
      MISTRAL_API_KEY: ${MISTRAL_API_KEY}
    volumes:
      - whisper_models:/app/whisper/

  background-tasks:
    image: sebania/sebania:${SEBANIA_VERSION:-0.1.0}
    build:
      <<: *build-sebania
    container_name: sebania-background-tasks
    environment:
      <<: *env-variables
    volumes:
      - whisper_models:/app/whisper/
    depends_on:
      <<: *db-healthy
    command: "python manage.py process_tasks"

  testcases:
    build:
      <<: *build-sebania
    container_name: sebania-testcases
    environment:
      DJANGO_SETTINGS_MODULE: sebania.settings.test
      DATABASE_HOST: db
      MISTRAL_API_KEY: ${MISTRAL_API_KEY}
      WHISPER_MODEL_DIRECTORY: /app/whisper/
    volumes:
      - whisper_models:/app/whisper/
    depends_on:
      <<: *db-healthy
    command: "python manage.py test --no-input"

volumes:
  sebania_data:
  whisper_models: