services:
 db:
   container_name: sebania-db
   image: postgres:17
   environment:
     POSTGRES_DB: ${DATABASE_NAME}
     POSTGRES_USER: ${DATABASE_USERNAME}
     POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
   ports:
     - "5432:5432"
   volumes:
     - sebania_data:/var/lib/postgresql/data
   env_file:
     - .env

 api:
   build: .
   container_name: sebania-api
   ports:
     - "8000:8000"
   depends_on:
     - db
   environment:
     DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
     DJANGO_SETTINGS_MODULE: Sebania.settings.development
     DEBUG: True
     DJANGO_LOGLEVEL: info
     DJANGO_ALLOWED_HOSTS: localhost,127.0.0.1
     DATABASE_ENGINE: postgresql_psycopg2
     DATABASE_NAME: ${DATABASE_NAME}
     DATABASE_USERNAME: ${DATABASE_USERNAME}
     DATABASE_PASSWORD: ${DATABASE_PASSWORD}
     DATABASE_HOST: ${DATABASE_HOST}
     DATABASE_PORT: ${DATABASE_PORT}
   env_file:
     - .env
volumes:
   sebania_data: