# Stage 1: Base build stage
FROM python:3.12-slim AS builder
 
# Create the app directory
RUN mkdir /app
 
# Set the working directory
WORKDIR /app
 
# Set environment variables to optimize Python
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1 
 
# Upgrade pip and install dependencies
RUN pip install --upgrade pip 
 
# Copy the requirements file first (better caching)
COPY requirements_ai.txt /app/
 
# Install Python dependencies
RUN pip install --no-cache-dir -r requirements_ai.txt
 
# Stage 2: Production stage
FROM python:3.12-slim

# Install ffmpeg for Whisper
RUN apt-get -y update
RUN apt-get install -y ffmpeg
 
RUN useradd -m -r appuser && \
   mkdir /app && \
   chown -R appuser /app
 
# Copy the Python dependencies from the builder stage
COPY --from=builder /usr/local/lib/python3.12/site-packages/ /usr/local/lib/python3.12/site-packages/
COPY --from=builder /usr/local/bin/ /usr/local/bin/
 
# Set the working directory
WORKDIR /app

# Create directory to store Whisper models
RUN mkdir /app/whisper/ && \
   chown -R appuser /app/whisper/
 
# Copy application code
COPY --chown=appuser:appuser .. .
 
# Set environment variables to optimize Python
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1 
 
# Switch to non-root user
USER appuser
 
# Start the application
CMD ["python", "manage.py", "process_tasks"]