# Generated by Django 5.1.8 on 2025-05-06 07:15

import base.models.vocal
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120, unique=True)),
                ('default', models.BooleanField(default=False)),
                ('categorie_default', models.CharField(max_length=30, null=True)),
                ('need_culture', models.BooleanField(default=False)),
                ('mots_cles', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Culture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=60, unique=True)),
                ('default', models.BooleanField(default=False)),
                ('categorie_default', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=100)),
                ('receiver', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('template_name', models.CharField(max_length=100)),
                ('template_context', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('error', models.TextField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MethodeAgricole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TypeParcelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Unite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('recolte_compatible', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Error',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField()),
                ('traceback', models.TextField()),
                ('url', models.URLField()),
                ('query_params', models.JSONField()),
                ('body', models.JSONField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ferme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('nom', models.CharField(max_length=80)),
                ('code_postal', models.CharField(blank=True, null=True)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('superficie_cultivee', models.FloatField(null=True)),
                ('employes', models.ManyToManyField(related_name='employes', to=settings.AUTH_USER_MODEL)),
                ('responsable', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='responsable', to=settings.AUTH_USER_MODEL)),
                ('methodes', models.ManyToManyField(to='base.methodeagricole')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CultureFerme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(max_length=30)),
                ('culture', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.culture')),
                ('ferme', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.ferme')),
            ],
            options={
                'db_table': 'base_culture_ferme',
            },
        ),
        migrations.CreateModel(
            name='ActiviteFerme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(max_length=30)),
                ('activite', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.activite')),
                ('ferme', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.ferme')),
            ],
            options={
                'db_table': 'base_activite_ferme',
            },
        ),
        migrations.CreateModel(
            name='Monitoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('url', models.URLField()),
                ('query_params', models.JSONField()),
                ('body', models.JSONField()),
                ('returned_status', models.IntegerField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Parcelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('nom', models.CharField(max_length=80)),
                ('superficie', models.FloatField(blank=True, null=True)),
                ('ferme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.ferme')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.typeparcelle')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vocal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateField()),
                ('audio', models.FileField(upload_to=base.models.vocal.get_upload_path)),
                ('transcription', models.TextField(blank=True, null=True)),
                ('transcribed_at', models.DateTimeField(null=True)),
                ('audio_to_transcription_duration', models.DurationField(blank=True, null=True)),
                ('output', models.JSONField(blank=True, null=True)),
                ('transcription_to_output_duration', models.DurationField(blank=True, null=True)),
                ('analyzed_at', models.DateTimeField(null=True)),
                ('finished_at', models.DateTimeField(null=True)),
                ('parcelles_non_trouvees', models.TextField(blank=True, null=True)),
                ('cultures_non_trouvees', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateField()),
                ('duree_minutes', models.IntegerField()),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('quantite', models.FloatField(blank=True, null=True)),
                ('nature', models.TextField(blank=True, null=True)),
                ('activite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.activite')),
                ('cultures', models.ManyToManyField(to='base.culture')),
                ('ferme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.ferme')),
                ('parcelles', models.ManyToManyField(to='base.parcelle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('unite', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.unite')),
                ('vocal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.vocal')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
