# Generated by Django 5.1.7 on 2025-04-11 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tache',
            name='nature',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tache',
            name='quantite',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tache',
            name='unite',
            field=models.TextField(blank=True, null=True),
        ),
    ]
