# Generated by Django 5.1.8 on 2025-05-07 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocal',
            name='errors',
            field=models.TextField(blank=True, null=True),
        ),
    ]
