# Generated by Django 5.1.8 on 2025-05-16 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_vocal_errors'),
    ]

    operations = [
        migrations.CreateModel(
            name='CultureTache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.FloatField(blank=True, null=True)),
                ('nature', models.TextField(blank=True, null=True)),
                ('culture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.culture')),
                ('parcelles', models.ManyToManyField(to='base.parcelle')),
                ('unite', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.unite')),
            ],
        ),
        migrations.AlterField(
            model_name='tache',
            name='cultures',
            field=models.ManyToManyField(to='base.culturetache'),
        ),
    ]
