# Generated by Django 5.1.7 on 2025-03-22 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_user_managers_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('default', models.BooleanField(default=False)),
                ('categorie_default', models.CharField(max_length=50, null=True)),
                ('need_culture', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Culture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True)),
                ('default', models.BooleanField(default=False)),
                ('categorie_default', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MethodeAgricole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('label', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='TypeParcelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Unite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('label', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='ActiviteUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(max_length=15)),
                ('activite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.activite')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'base_activite_user',
            },
        ),
        migrations.CreateModel(
            name='CultureUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(max_length=15)),
                ('culture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.culture')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'base_culture_user',
            },
        ),
        migrations.CreateModel(
            name='Ferme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('adresse', models.CharField(max_length=100)),
                ('superficie_cultivee', models.FloatField()),
                ('employes', models.ManyToManyField(related_name='employes', to=settings.AUTH_USER_MODEL)),
                ('responsable', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='responsable', to=settings.AUTH_USER_MODEL)),
                ('methodes', models.ManyToManyField(to='base.methodeagricole')),
            ],
        ),
        migrations.CreateModel(
            name='Parcelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
                ('superficie', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.typeparcelle')),
            ],
        ),
        migrations.AddField(
            model_name='culture',
            name='unite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.unite'),
        ),
    ]
