# Generated by Django 5.1.7 on 2025-04-29 06:10

import base.models.vocal
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_vocal'),
    ]

    operations = [
        migrations.AddField(
            model_name='tache',
            name='cultures_non_trouvees',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tache',
            name='parcelles_non_trouvees',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tache',
            name='vocal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.vocal'),
        ),
        migrations.AlterField(
            model_name='vocal',
            name='audio',
            field=models.FileField(upload_to=base.models.vocal.get_upload_path),
        ),
    ]
