# Generated by Django 5.1.8 on 2025-05-22 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_culturetache_alter_tache_cultures'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parcelle',
            name='superficie',
        ),
        migrations.AddField(
            model_name='parcelle',
            name='largeur',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parcelle',
            name='largeur_passe_pieds',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parcelle',
            name='longueur',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parcelle',
            name='nombre_planches',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
