# Generated by Django 5.1.7 on 2025-04-29 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_tache_cultures_non_trouvees_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocal',
            name='finished_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='vocal',
            name='queued_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='vocal',
            name='transcribed_at',
            field=models.DateTimeField(null=True),
        ),
    ]
