# Generated by Django 5.1.7 on 2025-03-23 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_activite_culture_methodeagricole_typeparcelle_unite_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiviteFerme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(max_length=15)),
                ('activite', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.activite')),
                ('ferme', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.ferme')),
            ],
            options={
                'db_table': 'base_activite_ferme',
            },
        ),
        migrations.CreateModel(
            name='CultureFerme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(max_length=15)),
                ('culture', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.culture')),
                ('ferme', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.ferme')),
            ],
            options={
                'db_table': 'base_culture_ferme',
            },
        ),
    ]
