# Generated by Django 5.1.7 on 2025-03-23 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_activiteferme_cultureferme'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=100)),
                ('receiver', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('template_name', models.CharField(max_length=100)),
                ('template_context', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('error', models.TextField(default=None, null=True)),
            ],
        ),
    ]
