# Generated by Django 5.1.8 on 2025-05-26 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_parcelle_superficie_parcelle_largeur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocal',
            name='origine',
            field=models.CharField(choices=[('taches', 'Taches'), ('parcelles', 'Parcelles')], default='taches'),
            preserve_default=False,
        ),
    ]
