# Generated by Django 5.1.8 on 2025-05-26 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_vocal_origine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activite',
            name='need_culture',
        ),
        migrations.AddField(
            model_name='activite',
            name='niveau_complexite',
            field=models.IntegerField(default=1),
        ),
    ]
