# Generated by Django 5.1.8 on 2025-05-27 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_activite_need_culture_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unite',
            name='recolte_compatible',
        ),
        migrations.AddField(
            model_name='activite',
            name='unites',
            field=models.ManyToManyField(to='base.unite'),
        ),
    ]
