# Generated by Django 5.1.8 on 2025-05-27 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_unite_recolte_compatible_activite_unites'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parcelle',
            old_name='largeur_passe_pieds',
            new_name='largeur_planche',
        ),
    ]
