# Generated by Django 5.1.8 on 2025-05-28 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_rename_largeur_passe_pieds_parcelle_largeur_planche'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcelle',
            name='largeur_passe_pieds',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parcelle',
            name='superficie',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='parcelle',
            name='largeur',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='parcelle',
            name='longueur',
            field=models.FloatField(null=True),
        ),
    ]
