# Generated by Django 5.1.8 on 2025-05-28 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_parcelle_largeur_passe_pieds_parcelle_superficie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcelle',
            name='superficie_cultivee',
            field=models.FloatField(null=True),
        ),
    ]
