# Generated by Django 5.1.8 on 2025-06-05 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_parcelle_superficie_cultivee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ferme',
            old_name='methodes',
            new_name='methodes_agricoles',
        ),
    ]
