# Generated by Django 5.1.8 on 2025-06-11 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_rename_methodes_ferme_methodes_agricoles'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='activiteferme',
            constraint=models.UniqueConstraint(fields=('activite', 'ferme'), name='unique_ferme_activite_combination'),
        ),
        migrations.AddConstraint(
            model_name='cultureferme',
            constraint=models.UniqueConstraint(fields=('culture', 'ferme'), name='unique_ferme_culture_combination'),
        ),
    ]
