"""
ERREURS GLOBALES
"""
ERROR_CODE_GLOBAL_UNKNOWN_ERROR = "unknown_error"
ERROR_CODE_GLOBAL_WRONG_ARG = "wrong_arg_for_method"

"""
ERREURS AUTHENTIFICATION
"""
ERROR_CODE_AUTH_USER_MUST_BE_AUTHENTICATED = "user_must_be_authenticated"

"""
ERREURS LIEES AUX USER
"""
ERROR_CODE_USER_NOT_FOUND = "user_not_found"
"""
ERREURS LIEES A LA FERME
"""
ERROR_CODE_FERME_NOT_FOUND_FOR_USER = "ferme_not_found_for_user"
ERROR_CODE_FERME_NOT_FOUND = "ferme_not_found"
"""
ERREURS LIEES AUX PARCELLES
"""
ERROR_CODE_PARCELLE_TYPE_NOT_FOUND = "parcelle_type_not_found"