name: Django CI

on:
  push:
    branches: [ "dev", "master" ]
  pull_request:
    branches: [ "master" ]


env:
  DATABASE_NAME: sebania
  DATABASE_USERNAME: sebania
  DATABASE_PASSWORD: sebania
  COMPOSE_BAKE: true
  MISTRAL_API_KEY: ${{ secrets.MISTRAL_API_KEY }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Create testing database and run testcases using Docker Compose
        run: docker compose up --build db testcases --abort-on-container-exit --exit-code-from testcases
      - name: Destroy testing database
        run: docker compose down -v
